### ISSUE TITLE
running node.py with an error

### ISSUE THREAD

**Issue by helxsz** [hclivess/Bismuth#180]
I am working on python2.7 and ubuntu 14.04, trying to install bismuth, but come up with a error.

```
2018-01-17 22:35:28,754 <module>(345) Configuration settings loaded
2018-01-17 22:35:28,754 keys_check(34) privkey.der found
2018-01-17 22:35:28,754 <module>(1584) Local address: 09e3054aed578e8ae9c834f51e35e978ab39450f602d1111eeeee259
2018-01-17 22:35:28,755 coherence_check(1606) Testing chain coherence
2018-01-17 22:35:29,803 coherence_check(1661) Chain coherence test complete for static/ledger.db
2018-01-17 22:35:29,845 coherence_check(1661) Chain coherence test complete for static/hyper.db
2018-01-17 22:35:29,848 ledger_convert(400) Recompressing hyperblocks (keeping full ledger)
2018-01-17 22:35:31,834 <module>(1680) Moving database to RAM
Traceback (most recent call last):
  File "node.py", line 1695, in <module>
    conn, c = db_c_define()
  File "node.py", line 322, in db_c_define
    return conn, c
```
what the problem could be like?

**Comment by EggPool** [comment]
Bismuth is meant to run on python3. Use Python3.6

**Comment by helxsz** [comment]
thanks
