### ISSUE TITLE
Exceptions while running a node

### ISSUE THREAD

**Issue by cryptonoob42** [hclivess/Bismuth#260]
Running a node on Ubuntu with release 4.2.4.5 yields a lot of exceptions like the following:

    2018-05-22 10:34:54,151 Status: Threads at 66 / 24
    2018-05-22 10:34:54,151 Status: Whitelist: ['127.0.0.1']
    2018-05-22 10:34:54,151 Status: Number of Outbound connections: 0
    2018-05-22 10:34:54,151 Status: MEMPOOL Frozen = 
    2018-05-22 10:34:54,152 Status: MEMPOOL Live = 
    2018-05-22 10:34:54,157 Status: MEMPOOL 0 Txs from 0 senders to 0 distinct recipients. Openfield len None
    2018-05-22 10:34:54,158 Status: Last block 653130 was generated 1162.51 minutes ago
    Exception in thread Thread-291:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "node.py", line 2167, in worker
        peer_ip = s.getpeername()[0]
    TypeError: 'NoneType' object is not subscriptable

**Comment by cryptonoob42** [comment]
Nota bene: running the wallet on Windows does not exhibit this behaviour.

**Comment by EggPool** [comment]
The module I personally use is PySocks
pip3 install PySocks

works on ubuntu

**Comment by hclivess** [comment]
Yeah, that's the one

**Comment by cryptonoob42** [comment]
Yeah the requirements-node.txt does state that PySocks is required, and I did install the requirements using pip. I assume that this might also be due to an outdated version or some sort of conflict. I would suggest the same solution as for issue #259 which is to specify a minimum required version in requirements-node.txt. Is this issue really resolved or why was it closed already?

**Comment by cryptonoob42** [comment]
The solution on my VM was to remove python3-socks via apt, then upgrade pysocks via pip to version 1.6.8. Maybe this should be documented somewhere.

**Comment by EggPool** [comment]
Thanks for the feedback, much appreciated!
Feel free to patch the requirements.txt with correct versions and submit a PR.

I'll also add that info to the linux install page.
