### ISSUE TITLE
bootstrap file(ledger.tar.gz) corrupted?

### ISSUE THREAD

**Issue by HeavensGold** [hclivess/Bismuth#319]
I tried to fresh start 'node.py' in my ubuntu(16.04) PC.
However, every time it couldn't extract the compressed bootstrap file(ledger.tar.gz), with the error message "EOFError: Compressed file ended before the end-of-stream marker was reached".

I also tried to download and to decompress the bootstrap file from the bismuth website but in vain.
I couldn't decompress the file.

tar -xvzf ldeger.tar.gz 

"gzip: stdin: unexpected end of file"
"tar: Error is not recoverable: exiting now"

Below is the complete error message from node.py:
###################################################
Database needs upgrading, bootstrapping...
Downloaded 41 %
Downloaded 82 %
Downloaded 100 %
Traceback (most recent call last):
  File "node.py", line 2580, in <module>
    result = u.fetchall()[10][2]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "node.py", line 2590, in <module>
    bootstrap()
  File "node.py", line 253, in bootstrap
    tar.extractall("static/")  # NOT COMPATIBLE WITH CUSTOM PATH CONFS
  File "/home/***/anaconda3/envs/py365/lib/python3.6/tarfile.py", line 2008, in extractall
    numeric_owner=numeric_owner)
  File "/home/***/anaconda3/envs/py365/lib/python3.6/tarfile.py", line 2050, in extract
    numeric_owner=numeric_owner)
  File "/home/***/anaconda3/envs/py365/lib/python3.6/tarfile.py", line 2120, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/***/anaconda3/envs/py365/lib/python3.6/tarfile.py", line 2169, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/home/***/anaconda3/envs/py365/lib/python3.6/tarfile.py", line 249, in copyfileobj
    buf = src.read(bufsize)
  File "/home/***/anaconda3/envs/py365/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/home/***/anaconda3/envs/py365/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/***/anaconda3/envs/py365/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by HeavensGold** [comment]
Thank you. I also confirm that it was solved.

2018년 8월 23일 (목) 오전 7:21, Jan Kučera <notifications@github.com>님이 작성:
